### PR TITLE
Merge into master

### PR DESCRIPTION
**Pull request by chilampoon**

### CODE REVIEW

**Comment by cookersjs** [comment]
For posterity, this merge is in preparation for publishing the package. CRAN prefers (requires?) that repositories be published using the 'master' branch of a project

**Review by cookersjs — APPROVED** [review]

**Comment by chilampoon** [comment]
> For posterity, this merge is in preparation for publishing the package. CRAN prefers (requires?) that repositories be published using the 'master' branch of a project

Thanks for the clarification! I was intended to submit the package to both CRAN and Bioconductor, but then I realized that it can only be submitted to one side, so I chose the Bioconductor side, not CRAN..

Also the submission guideline says `Assuming that your package is in a GitHub Repository and under the default ‘master’ branch.` Can the default branch be switched to 'master'? The default branch is still 'develop'.

**Comment by SolomonShorser-OICR** [comment]
@chilampoon Do you have a link to the guideline that says `Assuming that your package is in a GitHub Repository and under the default ‘master’ branch`? I think that was only an example, not a requirement, but I'd need to see the whole document to be sure.

**Comment by SolomonShorser-OICR** [comment]
@chilampoon I think I found it here: https://github.com/Bioconductor/Contributions#starting-the-submission-process

It looks like 'master' must be the default branch. :/

**Pull request merged**
